repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        entry: make lint
        language: system
        files: bills/.*, app/.*

  - repo: local
    hooks:
      - id: test
        name: Test
        entry: make test
        language: system
        files: bills/.*, app/.*
